# Docker image
image: ktmeaton/plague-phylogeography:dev

# Workspace startup tasks
# Setup pre-commit for workspace
tasks:
  - name: init workspace
    init: |
      echo "Initializing workspace..." \
      && export PIP_USER=false \
      && pre-commit install \
      && pre-commit install-hooks \
      && echo -e "\nWorkspace initialized."

  - name: main
    command: |
      echo "export PIP_USER=false" >> ~/.bashrc \
      && echo -e "\nMain terminal ready."

  - name: jupyter server
    command: jupyter notebook --NotebookApp.allow_origin=\'$(gp url 8888)\'

# Ports and opening instructions
ports:
  - port: 8888
    onOpen: notify
