nextflow run pipeline.nf \
  --ncbimeta_create ncbimeta.yaml \
  --ncbimeta_update ncbimeta.yaml \
  --ncbimeta_annot annot_biosample.txt \
  --max_datasets 10 \
  -with-trace \
  -with-timeline \
  -with-dag pipeline.pdf \
  -with-report \
  -name PlaguePhyloFull1 \
  -resume
