name: plague-phylogeography-0.1.4dev
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - sqlite=3.31.1
  - bioconda/label/cf201901::vt=2015.11.10
  - snippy=4.6.0
  - blast=2.9.0
  - mummer=3.23
  - vcftools=0.1.16
  - pip=20.0.2
  - ncbimeta=0.7.0
  - qualimap=2.2.2d
  - multiqc=1.8
  - nextflow=20.01.0
  - iqtree=2.0.3
  - sra-tools=2.10.3
  - graphviz=2.40.1
