name: plague-phylogeography-0.1.5dev
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - snakemake=5.23.0
  - samtools=1.10
  - bwa=0.7.17
  - biopython=1.76
