#------------------------------------------------------------------------------#
# Generic config
#------------------------------------------------------------------------------#
restart-times: 1
latency-wait: 60
use-conda: True
conda-frontend: mamba
rerun-incomplete:  True
printshellcmds: False
log-handler-script: "workflow/scripts/slack_log.py"

#------------------------------------------------------------------------------#
# System config
#------------------------------------------------------------------------------#
# Total resources for the entire workflow
# ex. 4 cpus, 4GB each (total 16GB), on one node
resources: [cpus=4, mem_mb=16000, load=100, nodes=1]
# Default resources for a job
default-resources: [cpus=1, mem_mb=2000, time_min=2, nodes=1, account="def-briang"]
# Maximum number of jobs to run
jobs : "10"
# Where to put the .snakemake directory
shadow-prefix: "/home/keaton/projects/def-briang/keaton/plague-phylogeography"
# slurm execution
cluster: "sbatch --parsable -t {resources.time_min} -A {resources.account} --cpus-per-task {resources.cpus} --mem-per-cpu={resources.mem_mb} -n {resources.nodes} -o workflow/logs_slurm/{rule}_{wildcards} -e workflow/logs_slurm/{rule}_{wildcards}"
#cluster-status: "workflow/scripts/slurm_status.py"
