channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- anaconda:bokeh=2.3.0
- anaconda:gfortran_linux-64
- augur=10.3.0
- bioconda::adapterremoval=2.3.1
- bioconda::adapterremovalfixprefix=0.0.5
- bioconda::angsd=0.933
- bioconda::bamutil=1.0.14
- bioconda::beast2=2.6.2
- bioconda::bedtools=2.29.2
- bioconda::bowtie2=2.4.1
- bioconda::bwa=0.7.17
- bioconda::circularmapper=1.93.5
- bioconda::damageprofiler=0.4.9
- bioconda::dedup=0.12.7
- bioconda::eigenstratdatabasetools=1.0.2
- bioconda::fastp=0.20.1
- bioconda::fastqc=0.11.9
- bioconda::freebayes=1.3.2
- bioconda::gatk4=4.1.7.0
- bioconda::hops=0.34
- bioconda::kraken2=2.0.9beta
- bioconda::mtnucratio=0.7
#- bioconda::multiqc=1.9
- bioconda::multivcfanalyzer=0.85.2
- bioconda::picard=2.22.9
- bioconda::pmdtools=0.60
- bioconda::preseq=2.0.3
#- bioconda::pysam=0.15.4
#- bioconda::qualimap=2.2.2d
- bioconda::rename=1.601
#- bioconda::samtools=1.9
- bioconda::sequencetools=1.4.0.6
- bioconda::sexdeterrmine=1.1.2
- bioconda::vcf2genome=0.91
- bioconda:snippy=4.6.0
- bioconda:snp-dists=0.7.0
- bioconda:sra-tools=2.10.8
- bioconda:vt=0.57721
- biopython=1.76
- blast=2.10.1
- cartopy=0.18.0
- conda-forge::biopython=1.76
- conda-forge::geopy=2.0.0
- conda-forge::libiconv=1.15
- conda-forge::markdown=3.2.2
- conda-forge::nbconvert=5.6.0
- conda-forge::openjdk=8.0.144
- conda-forge::pandas=1.0.4
- conda-forge::pigz=2.3.4
- conda-forge::pygments=2.6.1
- conda-forge::pymdown-extensions=7.1
- conda-forge::python=3.7.3
- conda-forge::r-ape
- conda-forge::xopen=0.9.0
- contextily=1.0.1
- descartes=1.1.0
- dill=0.3.3
- ete3=3.1.2
- ffmpeg=4.3.1
- flask=1.1.2
- geopandas=0.8.1
- graphviz=2.40.1
- ipywidgets=7.5.1
- plotly=4.12.0
- iqtree=2.0.3
- matplotlib=3.3.2
- mummer=3.23
- nextflow=20.04.1
- ncbimeta=0.7.0
- conda-forge::nodejs=13.13.0
- numpy=1.19.1
- pandas=1.0.4
- pip=20.2.3
- pre-commit=2.6.0
- python-dotenv=0.14.0
- python=3.7.3
- qualimap=2.2.2d
- samtools=1.10
- seaborn=0.11.1
- singularity=3.6.3
- slackclient=2.9.1
- snakemake=5.27.4
- sqlite=3.31.1
- vcftools=0.1.16
- pip:
  - git+https://github.com/ktmeaton/MultiQC.git@snippy
  - git+https://github.com/ktmeaton/treetime.git
  #- phylo-treetime==0.8.1
  - nextstrain-augur==10.3.0
  - bezier==2020.5.19
name: plague-phylogeography
