name: plague-phylogeography
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  # Snakemake Execution
  - python=3.7.3
  - sqlite=3.31.1
  - snakemake=5.27.4
  - flask=1.1.2
  - python-dotenv=0.14.0
  - slackclient=2.9.1
  - singularity=3.6.3
  - samtools=1.10
  # Development
  - pre-commit=2.6.0
  # Database
  - ncbimeta=0.7.0
  # Data Download
  - bioconda:sra-tools=2.10.8
  # nf-core/eager
  - nextflow=20.04.1
  - graphviz=2.40.1
  # Alignment
  - bioconda:snippy=4.6.0
  - bioconda:vt=0.57721
  # Phylogeny
  - iqtree=2.0.3
  # Plotting
  - matplotlib=3.3.2
  - pandas=1.0.4
  - numpy=1.19.1
  # Filtering
  - biopython=1.76
  - mummer=3.23
  - blast=2.10.1 # dustmasker
  #- bedtools=2.29.2
  - vcftools=0.1.16
  # QC
  - anaconda:gfortran_linux-64
  - qualimap=2.2.2d
  - pip=20.2.3
  - pip:
    - git+https://github.com/ktmeaton/MultiQC.git@snippy
