#------------------------------------------------------------------------------#
# Generic config
#------------------------------------------------------------------------------#
restart-times: 2
max-jobs-per-second: 1
latency-wait: 5
keep-going: True
rerun-incomplete:  True
printshellcmds: False
#log-handler-script: "workflow/scripts/slack_log.py"

#------------------------------------------------------------------------------#
# System config
#------------------------------------------------------------------------------#
# Total resources for the entire workflow
# ex. 4 cpus, 2GB each (total 8GB)
resources: [cpus=3, mem_mb=12000, load=100]
# Default resources for a job
default-resources: [cpus=1, mem_mb=4000, time_min=60]
# Maximum number of jobs to run
jobs : "4"
