# Snakemake Configuration File

# Conda Environments
#conda_eager_env : "nf-core-eager-2.2.0dev"

# SQLITE Parameters
sqlite_db : "yersinia_pestis_db.sqlite"
sqlite_select_command_asm : "SELECT AssemblyFTPGenbank FROM Master WHERE (BioSampleComment LIKE '%KEEP%Assembly%')"
#sqlite_select_command_sra : "SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (BioSampleComment LIKE '%KEEP: EAGER Ancient%')"
sqlite_select_command_ref : "SELECT AssemblyFTPGenbank FROM Master WHERE (BioSampleComment LIKE '%Reference%')"
max_datasets_assembly : 20
max_datasets_sra : 2

# Testing queries
sqlite_select_command_sra : "SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (SRARunAccession = 'SRR1048902' OR SRARunAccession = 'SRR1048905')"

#reference_locus : "AL590842"
#reference_locus_start : "0"
#reference_locus_end : "4653728"

# Eager param
eager_rev : "7b51863957"
eager_clip_readlength : 35
eager_bwaalnn : 0.01
eager_bwaalnl : 16
organism : "Yersinia pestis"

# Snippy Parameters
snippy_ctg_depth : 10
snippy_bam_depth : 3
snippy_base_qual : 20
snippy_map_qual : 30
snippy_min_frac : 0.9
snippy_mask_char : "X"
snippy_missing_data : 0

# IQTREE
#iqtree_model = "K3Pu+F+I"
iqtree_outgroup : "Reference"
iqtree_other : "--ufboot 1000 --alrt 1000"
iqtree_runs : 1
