#------------------------------------------------------------------------------#
# Generic config
#------------------------------------------------------------------------------#
restart-times: 2
max-jobs-per-second: 1
latency-wait: 5
use-singularity: True
use-conda: False
singularity-prefix: /scratch/keaton/singularity/
conda-frontend: mamba
rerun-incomplete:  True
printshellcmds: False
log-handler-script: "workflow/scripts/slack_log.py"

#------------------------------------------------------------------------------#
# System config
#------------------------------------------------------------------------------#
# Total resources for the entire workflow
# ex. 4 cpus, 4GB each (total 16GB), on one node
resources: [cpus=20, mem_mb=40000, load=100]
# Default resources for a job
default-resources: [cpus=1, mem_mb=2000, time_min=30, account="def-briang"]
# Maximum number of jobs to run
jobs : "20"
# Where to put the .snakemake directory
shadow-prefix: "/scratch/keaton/plague-phylogeography"
# slurm execution
cluster: "sbatch --parsable -t {resources.time_min} -A {resources.account} --cpus-per-task {resources.cpus} --mem-per-cpu={resources.mem_mb} -o workflow/logs_slurm/{rule}_%j.out -e workflow/logs_slurm/{rule}_%j.err --job-name {rule} --export=ALL,NXF_OPTS='-Xms50m -Xmx{resources.mem_mb}m',NXF_OFFLINE='TRUE'"
cluster-status: "workflow/scripts/slurm_status.py"
