name: default
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - sqlite=3.31.1
  - snakemake=5.25.0
  - flask=1.1.2
  - pre-commit=2.6.0
  - python-dotenv=0.14.0
  - slackclient=2.9.1
  - singularity=3.6.3
