name: Cache Test

# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/cache_test.yaml'
      - 'environment.yaml'

jobs:
  cache_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      # Cache and Restore the conda pkgs directory
      # Only if the environment.yaml file changes
      - name: cache conda packages
        uses: actions/cache@v2
        with:
          # Cache conda env, exclude test
          path: |
            /home/runner/miniconda/envs/test-env
          #key: conda-cache-${{ runner.os }}-${{ hashFiles('./environment.yaml') }}
          key: conda-env-cache-${{ runner.os }}-test1
      # Create env
      - name: create env
        shell: bash -l {0}
        run: |
          conda create -n test-env
          conda install -n test-env -c bioconda nextflow
      # Test env
      - name: test env
        shell: bash -l {0}
        run: |
          conda activate test-env
          nextflow -v
          conda deactivate
      # Check env
      - name: check env
        shell: bash -l {0}
        run: |
          conda env list
