name: Cache Test

# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/cache_test.yaml'
      - 'environment.yaml'

jobs:
  cache_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #------------------------------------------------------------------------#
      #                     Acquire env files and src code                     #
      #------------------------------------------------------------------------#
      # Install nf-core/eager
      - name: download nf-core/eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager
          nextflow pull nf-core/eager -r ${EAGER_NF_REV}
          nextflow run nf-core/eager -r ${EAGER_NF_REV} --help
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      # Cache and Restore the conda pkgs directory
      # Only if the environment.yml file changes
      - name: cache eager env
        uses: actions/cache@v2
        id: eager-env-cache
        with:
          # Cache conda env, exclude test
          path: |
            /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-cache-${{ runner.os }}-${{ hashFiles('/home/runner/.nextflow/assets/nf-core/eager/environment.yml') }}
      # Check env pre
      - name: check env pre
        shell: bash -l {0}
        run: |
          conda env list
          ls -l /home/runner/miniconda/envs/
          ls -l /home/runner/.nextflow/assets/nf-core/eager/environment.yml
      # Create env
      - name: create conda env
        if: steps.eager-env-cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${EAGER_CONDA_ENV} -c bioconda nextflow
          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz

      # Test env
      - name: test env
        shell: bash -l {0}
        run: |
          conda activate ${EAGER_CONDA_ENV}
          nextflow -v
          conda deactivate
      # Check env
      - name: check env
        shell: bash -l {0}
        run: |
          conda env list
