name: Cache Test

# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"


on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/cache_test.yaml'

jobs:
  cache_test:
    runs-on: ubuntu-latest
    steps:

      # 1. Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      # Cache and Restore the conda pkgs directory
      # Only if the environment.yaml file changes
      - name: cache conda packages
        uses: actions/cache@v2
        with:
          path: |
            /usr/share/miniconda/pkgs
          key: conda-cache-${{ runner.os }}-${{ hashFiles('environment.yaml') }}

      # 2. Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1

      # 3a. Install nf-core/eager
      - name: install nf nf-core/eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager
          nextflow pull nf-core/eager -r ${EAGER_NF_REV}
          nextflow run nf-core/eager -r ${EAGER_NF_REV} --help

      # 3b. Install nf-core/eager
      - name: install conda nf-core/eager
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${EAGER_CONDA_ENV} -c bioconda nextflow
          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz
          conda activate ${EAGER_CONDA_ENV}
          conda deactivate
