name: Cache Test

# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    NF_VER: "20.01.0"

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/cache_test.yaml'
      - 'environment.yaml'

jobs:
  cache_test:
    runs-on: ubuntu-latest
    steps:
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #------------------------------------------------------------------------#
      #                     Acquire env files and src code                     #
      #------------------------------------------------------------------------#
      # download nextflow pipelines
      - name: download nf-core/eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager
          nextflow pull nf-core/eager -r ${EAGER_NF_REV}
          nextflow run nf-core/eager -r ${EAGER_NF_REV} --help
          # Move env file into github workspace for hashing
          cp ~/.nextflow/assets/nf-core/eager/environment.yml \
            ./nf-core-eager.yaml
      - name: download ktmeaton/plague-phylogeography
        shell: bash -l {0}
        run: |
          nextflow pull ktmeaton/plague-phylogeography
          nextflow pull ktmeaton/plague-phylogeography -r ${PHYLO_NF_REV}
          nextflow run ktmeaton/plague-phylogeography --version
          # Move env files into github workspace for hashing
          cp ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml \
            ./ktmeaton-plague-phylogeography.yaml
          cp ~/.nextflow/assets/ktmeaton/plague-phylogeography/config/nextstrain.yaml \
            ./nextstrain.yaml
      #------------------------------------------------------------------------#
      #                        Setup conda environments                        #
      #------------------------------------------------------------------------#
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      # Restore (and later cache) the nf-core/eager conda env
      # Only if the environment yaml file changed
      - name: cache eager env
        uses: actions/cache@v2
        id: eager-env-cache
        with:
          path: |
            /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-cache-${{ runner.os }}-test2-${{ hashFiles('./nf-core-eager.yaml') }}
      # Restore (and later cache) the plague-phylogeography conda env
      # Only if the environment yaml file changed
      - name: cache plague-phylogeography env
        uses: actions/cache@v2
        id: plague-phylogeography-env-cache
        with:
          path: |
            /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-cache-${{ runner.os }}-test2-${{ hashFiles('./ktmeaton-plague-phylogeography.yaml') }}
      # Create env
      - name: create conda env
        if: steps.eager-env-cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${EAGER_CONDA_ENV} -c anaconda nextflow==${NF_VER}
          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz
      #------------------------------------------------------------------------#
      #                        Test conda environments                         #
      #------------------------------------------------------------------------#
      # Test env
      - name: test env
        shell: bash -l {0}
        run: |
          conda activate ${EAGER_CONDA_ENV}
          nextflow -v
          conda deactivate
