name: Cache Test

# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    NF_VER: "20.01.0"

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/cache_test.yaml'
      - 'environment.yaml'

jobs:
  cache_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #------------------------------------------------------------------------#
      #                     Acquire env files and src code                     #
      #------------------------------------------------------------------------#
      # download nextflow pipelines
      - name: download nf-core/eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager
          nextflow pull nf-core/eager -r ${EAGER_NF_REV}
          nextflow run nf-core/eager -r ${EAGER_NF_REV} --help
          # Move env file into github workspace for hashing
          cp ~/.nextflow/assets/nf-core/eager/environment.yml config/eager-environment.yaml
      # download plague-phylogeography
      #- name: download plague-phylogeography
      #------------------------------------------------------------------------#
      #                        Setup conda environments                        #
      #------------------------------------------------------------------------#
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      # Restore (and later cache) the eager conda env if the yaml file changed
      - name: cache eager env
        uses: actions/cache@v2
        id: eager-env-cache
        with:
          path: |
            /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-cache-${{ runner.os }}-test1-${{ hashFiles('config/eager-environment.yaml') }}
      # Create env
      - name: create conda env
        if: steps.eager-env-cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${EAGER_CONDA_ENV} -c anaconda nextflow==${NF_VER}
          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz
      #------------------------------------------------------------------------#
      #                        Test conda environments                         #
      #------------------------------------------------------------------------#
      # Test env
      - name: test env
        shell: bash -l {0}
        run: |
          conda activate ${EAGER_CONDA_ENV}
          nextflow -v
          conda deactivate
