name: Continuous Integration

# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    NEXTSTRAIN_CONDA_ENV: "nextstrain-8.0.0"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    NF_VER: "20.01.0"
    AUSPICE_VER: "2.17.0"

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/ci.yaml'
      - 'environment.yaml'

jobs:
  #----------------------------------------------------------------------------#
  #                       Dependency Installation                              #
  #----------------------------------------------------------------------------#
  install :
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      plague-phylogeography-cache-hit: ${{ steps.plague-phylogeography-env-cache.outputs.cache-hit }}
      eager-cache-hit: ${{ steps.eager-env-cache.outputs.cache-hit }}
      nextstrain-cache-hit: ${{ steps.nextstrain-env-cache.outputs.cache-hit }}
    steps:
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #------------------------------------------------------------------------#
      #                     Acquire env files and src code                     #
      #------------------------------------------------------------------------#
      # download nextflow pipelines
      - name: download nf-core/eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager
          nextflow pull nf-core/eager -r ${EAGER_NF_REV}
          nextflow run nf-core/eager -r ${EAGER_NF_REV} --help
          # Move env file into github workspace for hashing
          cp ~/.nextflow/assets/nf-core/eager/environment.yml \
            ./nf-core-eager.yaml
      - name: download ktmeaton/plague-phylogeography
        shell: bash -l {0}
        run: |
          nextflow pull ktmeaton/plague-phylogeography
          nextflow pull ktmeaton/plague-phylogeography -r ${PHYLO_NF_REV}
          nextflow run ktmeaton/plague-phylogeography --version
          # Move env files into github workspace for hashing
          cp ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml \
            ./ktmeaton-plague-phylogeography.yaml
          cp ~/.nextflow/assets/ktmeaton/plague-phylogeography/config/nextstrain.yaml \
            ./nextstrain.yaml
      #------------------------------------------------------------------------#
      #                      Restore (cache) conda environments                #
      #------------------------------------------------------------------------#
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      # Restore (and later cache) the nf-core/eager conda env
      # Only if the environment yaml file changed
      - name: cache eager env
        uses: actions/cache@v2
        id: eager-env-cache
        with:
          path: |
            /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-cache-${{ runner.os }}-test2-${{ hashFiles('./nf-core-eager.yaml') }}
      # Restore (and later cache) the plague-phylogeography conda env
      # Only if the environment yaml file changed
      - name: cache plague-phylogeography env
        uses: actions/cache@v2
        id: plague-phylogeography-env-cache
        with:
          path: |
            /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-cache-${{ runner.os }}-test2-${{ hashFiles('./ktmeaton-plague-phylogeography.yaml') }}
      # Restore (and later cache) the nextstrain conda env
      # Only if the nextstrain yaml file changed
      - name: cache nextstrain env
        uses: actions/cache@v2
        id: nextstrain-env-cache
        with:
          path: |
            /home/runner/miniconda/envs/nextstrain-8.0.0
          key: nextstrain-env-cache-${{ runner.os }}-test2-${{ hashFiles('./nextstrain.yaml') }}

      #------------------------------------------------------------------------#
      #                      Create conda environments                         #
      #------------------------------------------------------------------------#
      # create eager env
      - name: create nf-core/eager env
        if: steps.eager-env-cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${EAGER_CONDA_ENV} -c bioconda nextflow==${NF_VER}
          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz
      # Create plague-phylogeography env
      - name: create ktmeaton/plague-phylogeography env
        if: steps.plague-phylogeography-env-cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml
      # Create nextstrain env
      - name: create nextstrain env
        if: steps.nextstrain-env-cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/ktmeaton/plague-phylogeography/config/nextstrain.yaml
          conda activate ${NEXTSTRAIN_CONDA_ENV}
          npm install --global auspice@${AUSPICE_VER}
          conda deactivate
      #------------------------------------------------------------------------#
      #                        Test conda environments                         #
      #------------------------------------------------------------------------#
      # test eager env
      - name: test eager env
        shell: bash -l {0}
        run: |
          conda activate ${EAGER_CONDA_ENV}
          which nextflow
          nextflow -v
          conda deactivate
      # test plague-phylogeography env
      - name: test plague-phylogeography env
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          which nextflow
          nextflow -v
          conda deactivate
      # test nextstrain env
      - name: test nextstrain env
        shell: bash -l {0}
        run: |
          echo "conda activate ${NEXTSTRAIN_CONDA_ENV}"
          conda activate ${NEXTSTRAIN_CONDA_ENV}
          echo "which auspice"
          which auspice
          echo "auspice -v"
          auspice -v
          echo "conda deactivate"
          conda deactivate

  #----------------------------------------------------------------------------#
  #                       Assembled Genome Test                                #
  #----------------------------------------------------------------------------#
  assembly:
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      #------------------------------------------------------------------------#
      #                             Test Pipeline                              #
      #------------------------------------------------------------------------#
      # Run Assembly Pipeline (only if cache restored)
      - name: assembly pipeline
        if:  needs.install.outputs.plague-phylogeography-cache-hit == 'true'
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run ktmeaton/plague-phylogeography \
            --max_datasets_assembly 2 \
            --skip_sra_download \
            --skip_eager \
            --skip_outgroup_download \
            --outdir test
      #------------------------------------------------------------------------#
      #                             Artifact Upload                            #
      #------------------------------------------------------------------------#
      # Sqlite Import
      - name: artifact sqlite-import
        uses: actions/upload-artifact@v2
        with:
          name: sqlite-import
          path: test/sqlite_import/
      # Snippy Pairwise
      - name: artifact snippy-pairwise
        uses: actions/upload-artifact@v2
        with:
          name: snippy-pairwise
          path: test/snippy_pairwise/output10X/
      # IQTREE
      - name: artifact iqtree
        uses: actions/upload-artifact@v2
        with:
          name: iqtree
          path: test/iqtree/
      # MultiQC
      - name: artifact multiqc
        uses: actions/upload-artifact@v2
        with:
          name: multiqc
          path: test/multiqc/multiqc_report.html
      # Trace
      - name: artifact trace
        uses: actions/upload-artifact@v2
        with:
          name: trace
          path: test/trace/
#  sra :
