#------------------------------------------------------------------------------#
name: Docker
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/docker.yaml'
      - 'workflow/envs/*/*.yaml'
      - 'workflow/envs/*/Dockerfile'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
#------------------------------------------------------------------------------#
  push_dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ktmeaton/plague-phylogeography' }}
    strategy:
      matrix:
        env_name: ["align","eager","phylogeny","plot", "qc", "sra"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Check docker and conda changes
      - name: check for changes
        id: git-diff
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            workflow/envs/
          FILES: |
            Dockerfile
            *.yaml
      #------------------------------------------------------------------------#
      # Build
      - name: build docker image
        if: contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/${{ matrix.env_name }}/${{ matrix.env_name }}.yaml") || contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/${{ matrix.env_name }}/Dockerfile")
        run:
          cd workflow/envs/${{ matrix.env_name }};
          docker build --build-arg GIT_COMMIT=$(git log -1 --format=%h) --no-cache . -t ktmeaton/plague-phylogeography:${{ matrix.env_name }};
      #------------------------------------------------------------------------#
      # Deploy
      - name: push docker image
        if: contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/${{ matrix.env_name }}/${{ matrix.env_name }}.yaml") || contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/${{ matrix.env_name }}/Dockerfile")
        run:
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
          docker push ktmeaton/plague-phylogeography:${{ matrix.env_name }}
