#------------------------------------------------------------------------------#
name: Docker
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker.yaml'
      - 'workflow/envs/merge/environment.yaml'
      - 'workflow/envs/merge/Dockerfile'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  push_docker_dev:
    name: Push to Docker Hub (dev)
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Check only for changes in conda and dockerfile
      - name: check for changes
        id: git-diff
        uses: technote-space/get-diff-action@v4
        with:
          PREFIX_FILTER: |
            workflow/envs/merge/
          FILES: |
            Dockerfile
            environment.yaml
      # build docker image
      - name: docker build
        if: steps.git-diff.outputs.diff
        run: |
          cd workflow/envs/merge/;
          docker build --no-cache . -t ktmeaton/plague-phylogeography:dev;
      #------------------------------------------------------------------------#
      # tag and upload
      - name: docker push
        if: steps.git-diff.outputs.diff
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
          docker push ktmeaton/plague-phylogeography:dev;

  push_docker_release:
    name: Push to Docker Hub (release)
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        if: ${{ github.event_name == 'release' }}
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # build docker image
      - name: docker build
        if: ${{ github.event_name == 'release' }}
        run: |
          cd workflow/envs/main/;
          docker build --no-cache . -t ktmeaton/plague-phylogeography:${{ github.event.release.tag_name }};
      #------------------------------------------------------------------------#
      - name: docker push
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
          docker push ktmeaton/plague-phylogeography:${{ github.event.release.tag_name }};
