#------------------------------------------------------------------------------#
name: Docker
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'disblae'
    paths:
      - '.github/workflows/docker.yaml'
      - 'workflow/envs/*/*.yaml'
      - 'workflow/envs/*/Dockerfile'
  #pull_request:
  #  branches:
  #    - '*'
  #release:
  #  types: [published]
#------------------------------------------------------------------------------#
jobs:
#------------------------------------------------------------------------------#
  push_dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ktmeaton/plague-phylogeography' }}
    strategy:
      matrix:
        env_name: ["main"]
      # Don't cancel a matrix job if another job fails
      fail-fast: false
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Check docker and conda changes
      - name: check for changes
        id: git-diff
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            workflow/envs/main/
          FILES: |
            Dockerfile
            main.yaml
      #------------------------------------------------------------------------#
      # Build
      - name: build docker image
        if: env.GIT_DIFF
        run:
          cd workflow/envs/${{ matrix.env_name }};
          docker build --build-arg GIT_COMMIT=$(git log -1 --format=%h) --no-cache . -t ktmeaton/plague-phylogeography;
      #------------------------------------------------------------------------#
      # Deploy
      - name: push docker image
        if: env.GIT_DIFF
        run:
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
          docker push ktmeaton/plague-phylogeography
