#------------------------------------------------------------------------------#
name: Docker
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/docker.yaml'
      - 'workflow/envs/*/Dockerfile'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
#------------------------------------------------------------------------------#
  push_dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ktmeaton/plague-phylogeography' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Check docker and conda changes
      - name: check for changes
        id: git-diff
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            workflow/envs/
          FILES: |
            Dockerfile
            *.yaml
      #------------------------------------------------------------------------#
      # Plot environment
      - name: build PLOT docker image
        if: contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/plot/plot.yaml") || contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/plot/Dockerfile")
        run:
          cd workflow/envs/plot;
          docker build --no-cache . -t ktmeaton/plague-phylogeography:plot;
      #- name: push PLOT to DockerHub
      #  if: ${{ github.event_name == 'push' }}
      #  run: |
      #    echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      #    docker tag ktmeaton/plague-phylogeography:plot
      #    docker push ktmeaton/plague-phylogeography:plot
