#------------------------------------------------------------------------------#
name: Docker
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/docker.yaml'
      - 'workflow/envs/*/Dockerfile'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
#------------------------------------------------------------------------------#
  push_dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ktmeaton/plague-phylogeography' }}
    strategy:
      matrix:
        env_name: ["plot", "sra"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      #------------------------------------------------------------------------#
      # Check docker and conda changes
      - name: check for changes
        id: git-diff
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            workflow/envs/
          FILES: |
            Dockerfile
            *.yaml

      - name: test
        run: |
          echo ${{ matrix.env_name }}
      #------------------------------------------------------------------------#
      # Plot environment
      #- name: build docker image
      #  if: contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/plot/plot.yaml") || contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/plot/Dockerfile")
      #  run:
      #    cd workflow/envs/plot;
      #    docker build --no-cache . -t ktmeaton/plague-phylogeography:plot;

      #- name: push docker image
      #  if: contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/plot/plot.yaml") || contains(${{ steps.git-diff.outputs.diff }}, "workflow/envs/plot/Dockerfile")
      #  run:
      #    echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
      #    docker push ktmeaton/plague-phylogeography:plot
