#------------------------------------------------------------------------------#
name: Docker
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/docker.yaml'
      - 'workflow/envs/*/Dockerfile'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
#------------------------------------------------------------------------------#
  push_dockerhub:
    name: Push a docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ktmeaton/plague-phylogeography' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Plot Docker Image
      - name: check for changes - plot
        uses: technote-space/get-diff-action@v1
        with:
          FILES: |
            workflow/envs/plot/Dockerfile
            workflow/envs/plot/plot.yaml

      - name: build docker image - plot
        if: env.GIT_DIFF
        run:
          cd workflow/envs/plot;
          docker build --no-cache . -t ktmeaton/plague-phylogeography:plot;
      #------------------------------------------------------------------------#
      #- name: push to DockerHub
      #  if: ${{ github.event_name == 'push' }}
      #  run: |
      #    echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      #    docker tag ktmeaton/plague-phylogeography:plot
      #    docker push ktmeaton/plague-phylogeography:plot
