#------------------------------------------------------------------------------#
name: Docker
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker.yaml'
      - 'workflow/envs/main/main.yaml'
      - 'workflow/envs/main/Dockerfile'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  push_docker:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Check only for changes in conda and dockerfile
      - name: check for changes
        id: git-diff
        uses: technote-space/get-diff-action@v2
        with:
          PREFIX_FILTER: |
            workflow/envs/main/
          FILES: |
            Dockerfile
            main.yaml
      # build docker image
      - name: docker build
        if: steps.git-diff.outputs.diff
        run: |
          cd workflow/envs/main/;
          docker build --no-cache . -t ktmeaton/plague-phylogeography:latest;
      #------------------------------------------------------------------------#
      # tag and upload
      - name: docker push (dev)
        if: steps.git-diff.outputs.diff && ${{ github.event_name == 'push' }}
        #if: steps.git-diff.outputs.diff && ${{ github.event_name == 'push' }}
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
          docker tag ktmeaton/plague-phylogeography:latest ktmeaton/plague-phylogeography:dev;
          docker push ktmeaton/plague-phylogeography:dev;

      - name: docker push (release)
        if: steps.git-diff.outputs.diff
        #if: steps.git-diff.outputs.diff && ${{ github.event_name == 'release' }}
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
          docker push ktmeaton/plague-phylogeography:latest;
          docker tag ktmeaton/plague-phylogeography:latest ktmeaton/plague-phylogeography:${{ github.event.release.tag_name }};
          docker ktmeaton/plague-phylogeography:${{ github.event.release.tag_name }};
