#------------------------------------------------------------------------------#
name: Docs
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
    paths:
      - 'workflows/envs/*/Dockerfile'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
#----------------------------------------------------------------------------#
  push_dockerhub:
    name: Push a docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ktmeaton/plague-phylogeography' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: build docker image - plot
        run:
          cd workflow/envs/plot;
          docker build --no-cache . -t ktmeaton/plague-phylogeography:plot;
