#------------------------------------------------------------------------------#
name: Docs
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/docs.yaml'
      - 'docs/*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Compile the sphinx docs
  sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Install Dependencies
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install Sphinx
        run: |
          pip install sphinx sphinx-rtd-theme
          sphinx-build --version

      - name: Install Markdown 2 RST
        run: |
          pip install m2r
          m2r --version
      #------------------------------------------------------------------------#
      # Build Docs
      - name: Compile docs
        run: |
          m2r README.md
          mv README.md README.rst
          cd docs/
          make html
      #------------------------------------------------------------------------#
      # Artifact Uploads
      - name: artifact Docs HTML
        uses: actions/upload-artifact@v2
        with:
          name: docs-build-html
          path: docs/_build/*
