#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - master
      - dev
    paths:
      - '.github/workflows/install.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*/*.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  install_conda:
    name: Install with Conda
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      #------------------------------------------------------------------------#
      # Env setup
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
          echo "FLOWDASH_BIO_USERNAME=${{ secrets.FLOWDASH_BIO_USERNAME }}" >> $GITHUB_ENV
          echo "FLOWDASH_BIO_PASSWORD=${{ secrets.FLOWDASH_BIO_PASSWORD }}" >> $GITHUB_ENV
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      # Install conda environment
      - name: create conda env
        run: mamba env create -f workflow/envs/merge/environment.yaml
      # Install lsd2
      - name: install lsd2
        run: |
          wget https://github.com/tothuhien/lsd2/releases/download/v1.9.9/lsd2_unix ;
          mv lsd2_unix /home/runner/miniconda/envs/plague-phylogeography/bin/lsd2 ;
          conda activate plague-phylogeography ;
          which lsd2 ;
          lsd2 -h ;
      #------------------------------------------------------------------------#
      # run help
      - name: run help
        shell: bash -l {0}
        run: |
          conda activate plague-phylogeography;
          snakemake help --profile profiles/gh-actions --configfile results/config/snakemake.yaml ;
      #------------------------------------------------------------------------#
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
  #----------------------------------------------------------------------------#
  install_docker:
    name: Install with Docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      #------------------------------------------------------------------------#
      - name: setup environment variables
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}" >> $GITHUB_ENV
          echo "FLOWDASH_BIO_USERNAME=${{ secrets.FLOWDASH_BIO_USERNAME }}" >> $GITHUB_ENV
          echo "FLOWDASH_BIO_PASSWORD=${{ secrets.FLOWDASH_BIO_PASSWORD }}" >> $GITHUB_ENV
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # pull docker image
      - name: docker pull
        run: docker pull ktmeaton/plague-phylogeography:dev
      #------------------------------------------------------------------------#
      # run help
      - name: run help
        run: docker run -e FLOWDASH_BIO_USERNAME=$FLOWDASH_BIO_USERNAME -e FLOWDASH_BIO_PASSWORD=$FLOWDASH_BIO_PASSWORD -v $PWD:/pipeline -w /pipeline ktmeaton/plague-phylogeography:dev snakemake help --profile profiles/gh-actions --configfile results/config/snakemake.yaml;
