#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/install.yaml'
      - 'workflow/envs/default.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  install :
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache default env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/default
          key: snakemake-default-${{ runner.os }}-${{ hashFiles('workflow/env/default.yaml') }}
      # Check conda environments
      - name: check cache
        run: |
          conda info --envs
      # Create environment
      - name: create default environment
        shell: bash -l {0}
        run:
          mamba env create -f workflow/env/default.yaml
