#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/install.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*/*.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["--use-conda --conda-prefix /home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/conda", "--use-singularity --singularity-prefix /home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/singularity/"]
      fail-fast: false
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Setup python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # Setup snakemake
      - name: setup snakemake
        run: pip install snakemake==5.26.0 ftputil==4.0.0
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      # Setup singularity
      - name: setup singularity
        uses: eWaterCycle/setup-singularity@v3
        with:
          singularity-version: 3.6.3
      #------------------------------------------------------------------------#
      # install pipeline container
      - name: install container
        run: |
          snakemake --profile profiles/gh-actions ${{ matrix.container }} test_container;
      #------------------------------------------------------------------------#
      # run help
      - name: run help
        run: |
          snakemake --profile profiles/gh-actions ${{ matrix.container }} help;
