name: Install

# Global workflow environment variables
env:
    PHYLO_NF_REV: "master"
    EAGER_NF_REV: "7b51863957"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    NEXTSTRAIN_CONDA_ENV: "nextstrain-8.0.0"
    # Manually change this in the artifact section


#This is a workflow for installation testing.
on:
  # Triggered on Push for any branch
  push:
    branches:
      - '*'
    # On change to workflow, pipeline
    paths:
      - '.github/workflows/install.yaml'
      - 'nextflow.config'
      - 'environment.yaml'
      - 'config/nextstrain.yaml'

  # Triggered on PR for all branches, pipeline
  pull_request:
    branches:
      - '*'
  # Also on a published release
  release:
    types: [published]


jobs:

  nextflow:
    runs-on: ubuntu-latest
    steps:

      # 1. Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      # 2. Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true

      # 3a. Install ktmeaton/plague-phylogeography
      - name: install nf ktmeaton/plague-phylogeography
        shell: bash -l {0}
        run: |
          nextflow pull ktmeaton/plague-phylogeography
          nextflow pull ktmeaton/plague-phylogeography -r ${PHYLO_NF_REV}
          nextflow run ktmeaton/plague-phylogeography --version

      # 3b. Install ktmeaton/plague-phylogeography
      - name: install conda ktmeaton/plague-phylogeography
        shell: bash -l {0}
        run: |
          conda env create -f  ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml
          conda activate ${PHYLO_CONDA_ENV}
          conda list --export > ${PHYLO_CONDA_ENV}.txt
          cat ${PHYLO_CONDA_ENV}.txt
          conda deactivate

      # 4a. Install nf-core/eager
      - name: install nf nf-core/eager
        shell: bash -l {0}
        run: |
          nextflow pull nf-core/eager
          nextflow pull nf-core/eager -r ${EAGER_NF_REV}
          nextflow run nf-core/eager -r ${EAGER_NF_REV} --help

      # 4b. Install nf-core/eager
      - name: install conda nf-core/eager
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
          conda install -n ${EAGER_CONDA_ENV} -c bioconda nextflow
          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz
          conda activate ${EAGER_CONDA_ENV}
          conda list --export > ${EAGER_CONDA_ENV}.txt
          cat ${EAGER_CONDA_ENV}.txt
          conda deactivate

      # 5a. Install nextstrain
      - name: install conda nextstrain
        shell: bash -l {0}
        run: |
          conda env create -f ~/.nextflow/assets/ktmeaton/plague-phylogeography/config/nextstrain.yaml
          conda activate ${NEXTSTRAIN_CONDA_ENV}
          npm install --global auspice@2.17.0
          auspice --version
          conda list --export > ${NEXTSTRAIN_CONDA_ENV}.txt
          cat ${NEXTSTRAIN_CONDA_ENV}.txt
          conda deactivate

      # 6. Uplod conda export artifacts
      - name: artifact env-plague-phylogeography
        uses: actions/upload-artifact@v2
        with:
          name: env-plague-phylogeography
          path: ./plague-phylogeography-0.1.4dev.txt

      - name: artifact env-eager
        uses: actions/upload-artifact@v2
        with:
          name: env-eager
          path: ./nf-core-eager-2.2.0dev.txt

      - name: artifact env-nextstrain
        uses: actions/upload-artifact@v2
        with:
          name: env-nextstrain
          path: ./nextstrain-8.0.0.txt
