#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/install.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/default.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  install :
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      #------------------------------------------------------------------------#
      # Restore (cache) conda environments
      - name: cache default env
        id: cache-default
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/default
          key: snakemake-default-${{ hashFiles('workflow/envs/default.yaml') }}
      # Restore (cache) workflow environments
      #- name: cache workflow envs
      #  uses: actions/cache@v2
      #  with:
      #    path: /home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/conda
      #    key: snakemake-workflow-envs-${{ runner.os }}-${{ hashFiles('workflow/envs/*.yaml') }}
      # Check conda environments
      - name: check cache
        run: |
          conda info --envs
      # Create environment (if not cached)
      - name: create default environment
        if: steps.cache-default.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run:
          mamba env create -f workflow/envs/default.yaml;
      #------------------------------------------------------------------------#
      #  Install workflow conda environments
      - name: test conda install
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba --conda-create-envs-only all;
          conda deactivate;

      #  Test pipeline
      - name: test pipeline help and report
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake  --profile profiles/gh-actions --use-conda --conda-frontend mamba --report workflow/report/report.html help;
          conda deactivate;
