#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    NEXTSTRAIN_CONDA_ENV: "nextstrain-8.0.0"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    NF_VER: "20.01.0"
    AUSPICE_VER: "2.17.0"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/install.yaml'
      - 'environment.yaml'
      - 'config/nextstrain.yaml'
      - 'scripts/install.sh'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  install :
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache eager env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-${{ runner.os }}-7b51863957

      - name: cache plague-phylogeography env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-${{ runner.os }}-${{ hashFiles('environment.yaml') }}

      - name: cache nextstrain env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/nextstrain-8.0.0
          key: nextstrain-env-${{ runner.os }}-${{ hashFiles('config/nextstrain.yaml') }}

      #------------------------------------------------------------------------#
      # Download pipelines and install
      - name: install
        shell: bash -l {0}
        run: scripts/install.sh
      #------------------------------------------------------------------------#
      # Test conda environments
      - name: test eager env
        shell: bash -l {0}
        run: |
          conda activate ${EAGER_CONDA_ENV}
          which nextflow
          nextflow -v
          conda deactivate

      - name: test plague-phylogeography env
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          which nextflow
          nextflow -v
          conda deactivate

      - name: test nextstrain env
        shell: bash -l {0}
        run: |
          echo "conda activate ${NEXTSTRAIN_CONDA_ENV}"
          conda activate ${NEXTSTRAIN_CONDA_ENV}
          which auspice
          auspice -v
          conda deactivate
