#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    SINGULARITY_PREFIX: "/home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/singularity/"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/install.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*/*.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  install :
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_mode: ["conda", "singularity"]
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # Setup snakemake
      - name: setup snakemake
        run: pip install snakemake==5.26.0
      # Setup conda with mamba
      - name: setup conda
        if: matrix.container_mode == "conda"
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      # Setup singularity
      - setup singularity
        uses: eWaterCycle/setup-singularity@v3
        if: matrix.container_mode == "singularity"
        with:
          singularity-version: 3.6.3
      #------------------------------------------------------------------------#
      # Cache workflow environments
      #- name: cache workflow envs
      #  uses: actions/cache@v2
      #  with:
      #    path: /home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/conda
      #    key: snakemake-workflow-envs-${{ runner.os }}-${{ hashFiles('workflow/envs/main/main.yaml') }}
      # Check conda environments
      #- name: check cache
      #  run: |
      #    conda info --envs
      # Set up .env file with secrets
      #- name: create env file
      #  run:
      #    echo "export SLACK_TOKEN=${{ secrets.SLACK_GH_ACTIONS }}" > .env
      #------------------------------------------------------------------------#
      #  Install workflow conda environments
      #- name: test conda install
      #  shell: bash -l {0}
      #  run:
      #    conda activate plague-phylogeography;
      #    snakemake --use-conda --profile profiles/gh-actions --conda-create-envs-only all;
      #    conda deactivate;

      #  Test pipeline
      #- name: test pipeline help and report
      #  shell: bash -l {0}
      #  run:
      #    conda activate plague-phylogeography;
      #    snakemake --use-conda --profile profiles/gh-actions --report workflow/report/report.html help;
      #    conda deactivate;
