#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    SINGULARITY_PREFIX: "/home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/singularity/"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/install.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*/*.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  install_conda:
    name: Install with Conda
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Setup python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # Setup snakemake
      - name: setup snakemake
        run: pip install snakemake==5.26.0
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      #------------------------------------------------------------------------#
      # install pipeline env
      - name: create conda environment
        run: |
          snakemake --profile profiles/gh-actions --use-conda --conda-create-envs-only all
      # test pipeline
      - name: test help
        run: snakemake --profile profiles/gh-actions help
  #----------------------------------------------------------------------------#
  install_singularity:
    name: Install with Singularity
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Setup python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # Setup snakemake
      - name: setup snakemake
        run: pip install snakemake==5.26.0
      #------------------------------------------------------------------------#
      # Setup singularity
      - name: setup singularity
        uses: eWaterCycle/setup-singularity@v3
        with:
          singularity-version: 3.6.3
      #------------------------------------------------------------------------#
      # install pipeline env
      - name: create conda environment
        run: |
          snakemake --profile profiles/gh-actions --use-singularity help;
      # test pipeline
      - name: test help
        run: snakemake --profile profiles/gh-actions help;
