#------------------------------------------------------------------------------#
name: Pipeline
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*.yaml'
      - 'workflow/scripts/*'
      - 'results/import/*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  pipeline :
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      #------------------------------------------------------------------------#
      # Timezone setup
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/New_York
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache default env
        id: cache-default
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/default
          key: snakemake-default-env-${{ hashFiles('workflow/envs/default.yaml') }}
      # Cache workflow environments
      - name: cache workflow envs
        uses: actions/cache@v2
        with:
          path: /home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/conda
          key: snakemake-workflow-envs-${{ runner.os }}-${{ hashFiles('workflow/envs/*.yaml') }}
      # Check conda environments
      - name: check cache
        run: |
          conda info --envs
      # Create environment (if not cached)
      - name: create default environment
        if: steps.cache-default.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run:
          mamba env create -f workflow/envs/default.yaml;
      # Set up .env file with secrets
      - name: create env file
        run:
          echo "export SLACK_TOKEN=${{ secrets.SLACK_GH_ACTIONS }}" > .env
      #------------------------------------------------------------------------#
      # Test Data Download
      - name: test download
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba --log-handler-script workflow/scripts/slack_log.py test_download_ref test_download_fna test_download_sra test_download_gff test_download_gbff;
          conda deactivate
      # Test Eager
      - name: test eager
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba --log-handler-script workflow/scripts/slack_log.py test_eager_tsv_local test_eager_tsv_sra test_eager_local test_eager_sra;
          conda deactivate
      # Test snippy
      - name: test snippy pairwise
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba --log-handler-script workflow/scripts/slack_log.py test_snippy_pairwise_assembly test_snippy_pairwise_bam_sra test_snippy_pairwise_bam_local;
          conda deactivate
      # Test snippy multi
      - name: test snippy multi
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba --log-handler-script workflow/scripts/slack_log.py  test_snippy_multi test_snippy_multi_filter;
          conda deactivate
      # Test IQTREE
      - name: test iqtree
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba --log-handler-script workflow/scripts/slack_log.py  test_iqtree;
          conda deactivate
      # Test IQTREE
      - name: test multiqc
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba --log-handler-script workflow/scripts/slack_log.py  test_multiqc;
          conda deactivate
      # Test Report Generation
      - name: test report
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --report workflow/report/report.html all;
          conda deactivate
      #------------------------------------------------------------------------#
      #  Artifact Upload Report
      - name: artifact report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: workflow/report/report.html
      #  Artifact Upload logs
      - name: artifact logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: workflow/logs/
