#------------------------------------------------------------------------------#
name: Pipeline Local
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV:    "7b51863957"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    GH_RESOURCES:    "--max_memory 6.GB --max_cpus 2"
    SQLITE_DB_PATH:  "/home/runner/.nextflow/assets/${GITHUB_REPOSITORY}/results/ncbimeta_db/update/latest/output/database/yersinia_pestis_db.sqlite"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline_local.yaml'
      - 'main.nf'
      - 'nextflow.config'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  local :
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache eager env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-${{ runner.os }}-7b51863957

      - name: cache plague-phylogeography env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-${{ runner.os }}-${{ hashFiles('environment.yaml') }}

      - name: cache nextstrain env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/nextstrain-8.0.0
          key: nextstrain-env-${{ runner.os }}-${{ hashFiles('config/nextstrain.yaml') }}
      #------------------------------------------------------------------------#
      # Check conda environments
      - name: check cache
        run: conda info --envs
      #------------------------------------------------------------------------#
      # Download pipelines and install
      - name: install
        shell: bash -l {0}
        run: scripts/install.sh ${{github.repository}} ${{ github.sha }}
      #------------------------------------------------------------------------#
      #  Analyze Local Data
      - name: pipeline local
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run -r ${{ github.sha }} ${{github.repository}} \
            --skip_assembly_download \
            --skip_outgroup_download \
            --skip_sra_download \
            --eager_tsv "custom/local_data_eager.tsv" \
            --assembly_local "custom/*.fna" \
            --outdir test \
            ${GH_RESOURCES}
          conda deactivate
      #------------------------------------------------------------------------#
      #  Artifact Upload
      - name: artifact multiqc-eager
        uses: actions/upload-artifact@v2
        with:
          name: multiqc-eager
          path: test/eager/MultiQC/

      - name: artifact snippy-pairwise
        uses: actions/upload-artifact@v2
        with:
          name: snippy-pairwise
          path: test/snippy_pairwise/output10X/

      - name: artifact iqtree
        uses: actions/upload-artifact@v2
        with:
          name: iqtree
          path: test/iqtree/

      - name: artifact multiqc
        uses: actions/upload-artifact@v2
        with:
          name: multiqc
          path: test/multiqc/multiqc_report.html

      - name: artifact trace
        uses: actions/upload-artifact@v2
        with:
          name: trace
          path: test/trace/
