#------------------------------------------------------------------------------#
name: Pipeline CI
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    CONDA_SNK_PREFIX: "/home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/conda"
    SINGULARITY_SNK_PREFIX: "/home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/singularity/"
    TEST_DOWNLOAD: "test_download_reference test_download_assembly test_download_sra test_download_gff test_download_gbff"
    TEST_EAGER: "test_eager_local test_eager_sra"
    TEST_SNIPPY: "test_snippy_pairwise_assembly test_snippy_pairwise_sra test_snippy_pairwise_local"
    TEST_SNIPPY_MULTI: "test_snippy_multi test_snippy_multi_filter"
    TEST_PHYLOGENY: "test_iqtree"
    TEST_QC: "test_multiqc"

#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*/*.yaml'
      - 'workflow/envs/*/Dockerfile'
      - 'workflow/scripts/*'
      - 'results/sqlite_db/*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Conda Pipeline
  pipeline_conda:
    name: Pipeline with Conda
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 120
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      # Install conda environment
      - name: create conda env
        run: mamba env create -f workflow/envs/merge/environment.yaml;
      #------------------------------------------------------------------------#
      # Test Data Download
      - name: test download
        shell: bash -l {0}
        run: |
            conda activate plague-phylogeography;
            snakemake --profile profiles/gh-actions --use-conda --conda-prefix ${CONDA_SNK_PREFIX} ${TEST_DOWNLOAD};
      # Test eager
      #- name: test nf-core/eager
      #  shell: bash -l {0}
      #  run: |
      #      conda activate plague-phylogeography;
      #      snakemake --profile profiles/gh-actions --use-conda --conda-prefix ${CONDA_SNK_PREFIX} ${TEST_EAGER};
  #----------------------------------------------------------------------------#
  pipeline_singularity:
    name: Pipeline with Singularity
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup singularity
      - name: setup singularity
        uses: eWaterCycle/setup-singularity@v3
        with:
          singularity-version: 3.6.3
      #------------------------------------------------------------------------#
      # pull container
      - name: pull container
        run: singularity pull docker://docker.io/ktmeaton/plague-phylogeography:dev
      #------------------------------------------------------------------------#
      # test download
      - name: test download
        run: |
          singularity exec plague-phylogeography_dev.sif snakemake --use-singularity --singularity-prefix ${SINGULARITY_SNK_PREFIX} --profile profiles/gh-actions ${TEST_DOWNLOAD};
