name: Pipeline Assembly
#This is a workflow for testing assembly datasets only.

# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"

on:
  # Triggered on Push for any branch
  push:
    branches:
      - '*'
    # On change to workflow, pipeline
    paths:
      - '.github/workflows/pipeline_assembly.yaml'
      - 'main.nf'
      - 'nextflow.config'
      #- 'environment.yaml'

  # Triggered on PR for all branches, pipeline
  pull_request:
    branches:
      - '*'
  # Also on a published release
  release:
    types: [published]

jobs:

  # Install the pipeline and dependencies
  pipeline:
    runs-on: ubuntu-latest
    steps:
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #------------------------------------------------------------------------#
      #                     Acquire env files and src code                     #
      #------------------------------------------------------------------------#
      # download nextflow pipelines
      - name: download ktmeaton/plague-phylogeography
        shell: bash -l {0}
        run: |
          nextflow pull ktmeaton/plague-phylogeography
          nextflow run ktmeaton/plague-phylogeography --version
          # Move env files into github workspace for hashing
          cp ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml \
            ./ktmeaton-plague-phylogeography.yaml
      #------------------------------------------------------------------------#
      #                      Restore (cache) conda environments                #
      #------------------------------------------------------------------------#
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      # Restore the plague-phylogeography conda env
      # Only if the environment yaml file changed
      - name: cache plague-phylogeography env
        uses: actions/cache@v2
        id: plague-phylogeography-env-cache
        with:
          path: |
            /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-cache-${{ runner.os }}-test2-${{ hashFiles('./ktmeaton-plague-phylogeography.yaml') }}
      # Check environment restore
      - name: check conda
        run: conda info --envs
      #------------------------------------------------------------------------#
      #                             Test Pipeline                              #
      #------------------------------------------------------------------------#
      # Run Assembly Pipeline (only if cache restored)
      - name: assembly pipeline
        if: steps.plague-phylogeography-env-cache.outputs.cache-hit == 'true'
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run ktmeaton/plague-phylogeography \
            --max_datasets_assembly 2 \
            --skip_sra_download \
            --skip_eager \
            --skip_outgroup_download \
            --outdir test
      #------------------------------------------------------------------------#
      #                             Artifact Upload                            #
      #------------------------------------------------------------------------#
      # Sqlite Import
      - name: artifact sqlite-import
        uses: actions/upload-artifact@v2
        with:
          name: sqlite-import
          path: test/sqlite_import/
      # Snippy Pairwise
      - name: artifact snippy-pairwise
        uses: actions/upload-artifact@v2
        with:
          name: snippy-pairwise
          path: test/snippy_pairwise/output10X/
      # IQTREE
      - name: artifact iqtree
        uses: actions/upload-artifact@v2
        with:
          name: iqtree
          path: test/iqtree/
      # MultiQC
      - name: artifact multiqc
        uses: actions/upload-artifact@v2
        with:
          name: multiqc
          path: test/multiqc/multiqc_report.html
      # Trace
      - name: artifact trace
        uses: actions/upload-artifact@v2
        with:
          name: trace
          path: test/trace/
