#------------------------------------------------------------------------------#
name: Pipeline SRA
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV: "7b51863957"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    GH_RESOURCES:    "--max_memory 6.GB --max_cpus 2"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline_sra.yaml'
      - 'main.nf'
      - 'nextflow.config'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  sra :
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache eager env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-${{ runner.os }}-7b51863957

      - name: cache plague-phylogeography env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-${{ runner.os }}-${{ hashFiles('environment.yaml') }}

      - name: cache nextstrain env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/nextstrain-8.0.0
          key: nextstrain-env-${{ runner.os }}-${{ hashFiles('config/nextstrain.yaml') }}
      #------------------------------------------------------------------------#
      # Check conda environments
      - name: check cache
        run: conda info --envs
      #------------------------------------------------------------------------#
      # Download pipelines and install
      - name: install
        shell: bash -l {0}
        run: scripts/install.sh
      #------------------------------------------------------------------------#
      #  Download SRA Data
      - name: pipeline sra download
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run -r ${GITHUB_SHA} ${GITHUB_REPOSITORY} \
            --skip_assembly_download \
            --max_datasets_assembly 1 \
            --sqlite_select_command_sra "\"SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (SRARunAccession = 'SRR1048902' OR SRARunAccession = 'SRR1048905')\"" \
            --max_datasets_sra 2 \
            --skip_eager \
            --skip_outgroup_download \
            --outdir test \
            ${GH_RESOURCES}
          conda deactivate
      #  SRA Analysis Pipeline
      - name: pipeline sra analysis
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run -r ${GITHUB_SHA} ${GITHUB_REPOSITORY} \
            --skip_assembly_download \
            --max_datasets_assembly 1 \
            --sqlite_select_command_sra "\"SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (SRARunAccession = 'SRR1048902' OR SRARunAccession = 'SRR1048905')\"" \
            --max_datasets_sra 2 \
            --skip_outgroup_download \
            --outdir test \
            -resume \
            ${GH_RESOURCES}
          conda deactivate
