#------------------------------------------------------------------------------#
name: Pipeline CI
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*/*.yaml'
      - 'workflow/envs/*/Dockerfile'
      - 'workflow/scripts/*'
      - 'results/sqlite_db/*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Conda Pipeline
  pipeline_conda:
    name: Pipeline with Conda
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 60
    steps:
      #------------------------------------------------------------------------#
      # Env setup
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      # Install conda environment
      - name: create conda env
        run: mamba env create -f workflow/envs/merge/environment.yaml;
      #------------------------------------------------------------------------#
      # Test Data Download
      - name: run help
        shell: bash -l {0}
        run: |
            conda activate plague-phylogeography;
            snakemake --profile profiles/gh-actions help;
      # run all
      - name: run all
        shell: bash -l {0}
        run: |
            conda activate plague-phylogeography;
            snakemake --profile profiles/gh-actions all;
      # run report
      #- name: run report
      #  shell: bash -l {0}
      #  run: |
      #      conda activate plague-phylogeography;
      #      snakemake --profile profiles/gh-actions --report workflow/report/report.html all;
      #------------------------------------------------------------------------#
      #  Artifact Upload
      #- name: artifact conda-report
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: conda-report
      #    path: workflow/report/report.html
  #----------------------------------------------------------------------------#
  pipeline_singularity:
    name: Pipeline with Singularity
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 60
    steps:
      #------------------------------------------------------------------------#
      - name: setup environment variables
        run: |
          echo "SINGULARITY_DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "SINGULARITY_DOCKER_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}" >> $GITHUB_ENV
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup singularity
      - name: setup singularity
        uses: eWaterCycle/setup-singularity@v3
        with:
          singularity-version: 3.6.3
      #------------------------------------------------------------------------#
      # pull container
      - name: pull container
        run: singularity pull docker://docker.io/ktmeaton/plague-phylogeography:dev
      #------------------------------------------------------------------------#
      # Configure sra-toolkit
      - name: configure sra-toolkit
        run: |
          mkdir -p ~/.ncbi/;
          printf '/LIBS/GUID = "%s"\n' `uuidgen` > ~/.ncbi/user-settings.mkfg;
      # run help
      - name: run help
        run: singularity exec plague-phylogeography_dev.sif snakemake --profile profiles/gh-actions help;
      # run all
      - name: run all
        run: singularity exec plague-phylogeography_dev.sif snakemake --profile profiles/gh-actions all;
      # run report
      #- name: run report
      #  shell: bash -l {0}
      #  run: singularity exec plague-phylogeography_dev.sif snakemake --profile profiles/gh-actions --report workflow/report/report.html all;
      #------------------------------------------------------------------------#
      #  Artifact Upload
      #- name: artifact singularity-report
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: singularity-report
      #    path: workflow/report/report.html
  #----------------------------------------------------------------------------#
  pipeline_docker:
    name: Pipeline with Docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 60
    steps:
      #------------------------------------------------------------------------#
      - name: setup environment variables
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}" >> $GITHUB_ENV
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # pull docker image
      - name: docker pull
        run: docker pull ktmeaton/plague-phylogeography:dev
      #------------------------------------------------------------------------#
      # run help
      - name: run help
        run: docker run -v $PWD:/pipeline -w /pipeline ktmeaton/plague-phylogeography:dev snakemake --profile profiles/gh-actions help;
      # run all
      - name: run all
        shell: bash -l {0}
        run: docker run -v $PWD:/pipeline -w /pipeline ktmeaton/plague-phylogeography:dev snakemake --profile profiles/gh-actions all;
      # run report
      #- name: run report
      #  shell: bash -l {0}
      #  run: docker run -v $PWD:/pipeline -w /pipeline ktmeaton/plague-phylogeography:dev snakemake --profile profiles/gh-actions --report workflow/report/report.html all;
      #------------------------------------------------------------------------#
      #  Artifact Upload
      #- name: artifact docker-report
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: docker-report
      #    path: workflow/report/report.html
