#------------------------------------------------------------------------------#
name: Pipeline Assembly
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/pipeline_assembly.yaml'
      - 'main.nf'
      - 'nextflow.config'
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Assembled Genome Test
  assembly:
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #------------------------------------------------------------------------#
      # download nextflow pipelines
      - name: download ktmeaton/plague-phylogeography
        shell: bash -l {0}
        run: |
          nextflow pull ktmeaton/plague-phylogeography
          nextflow pull ktmeaton/plague-phylogeography -r ${GITHUB_SHA}
          # Move env files into github workspace for hashing
          cp ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml \
            ./ktmeaton-plague-phylogeography.yaml
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1

      - name: restore cache
        uses: actions/cache@v2
        id: plague-phylogeography-env-cache-restore
        with:
          path: |
            /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-cache-${{ runner.os }}-test2-${{ hashFiles('./ktmeaton-plague-phylogeography.yaml') }}
      #------------------------------------------------------------------------#
      # Check conda environments
      - name: check cache
        run: conda info --envs
      #  Fail workflow if cache not restored
      - name: fail cache
        if:  steps.plague-phylogeography-env-cache-restore.outputs.cache-hit != 'true'
        run: |
          echo "plague-phylogeography cache failed to load."
          exit 1
      #------------------------------------------------------------------------#
      #  Test Pipeline
      - name: pipeline
        if:  steps.plague-phylogeography-env-cache-restore.outputs.cache-hit == 'true'
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run -r ${GITHUB_SHA} ktmeaton/plague-phylogeography \
            --max_datasets_assembly 2 \
            --skip_sra_download \
            --skip_eager \
            --skip_outgroup_download \
            --outdir test
      #------------------------------------------------------------------------#
      #  Artifact Upload
      - name: artifact sqlite-import
        uses: actions/upload-artifact@v2
        with:
          name: sqlite-import
          path: test/sqlite_import/

      - name: artifact snippy-pairwise
        uses: actions/upload-artifact@v2
        with:
          name: snippy-pairwise
          path: test/snippy_pairwise/output10X/

      - name: artifact iqtree
        uses: actions/upload-artifact@v2
        with:
          name: iqtree
          path: test/iqtree/

      - name: artifact multiqc
        uses: actions/upload-artifact@v2
        with:
          name: multiqc
          path: test/multiqc/multiqc_report.html

      - name: artifact trace
        uses: actions/upload-artifact@v2
        with:
          name: trace
          path: test/trace/
