#------------------------------------------------------------------------------#
name: Pipeline
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*.yaml'
      - 'workflow/scripts/*'
      - 'results/import/*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  pipeline :
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache default env
        id: cache-default
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/default
          key: snakemake-default-env-${{ hashFiles('workflow/envs/default.yaml') }}
      # Cache workflow environments
      #- name: cache workflow envs
      #  uses: actions/cache@v2
      #  with:
      #    path: /home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/conda
      #    key: snakemake-workflow-envs-${{ runner.os }}-${{ hashFiles('workflow/envs/*.yaml') }}
      # Check conda environments
      - name: check cache
        run: |
          conda info --envs
      # Create environment (if not cached)
      - name: create default environment
        if: steps.cache-default.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run:
          mamba env create -f workflow/envs/default.yaml;
      #------------------------------------------------------------------------#
      # Test Data Download
      - name: test download
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_download_ref test_download_fna test_download_sra test_download_gff test_download_gbff;
          conda deactivate
      # Test Eager tsv
      - name: test eager tsv
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_eager_tsv_local test_eager_tsv_sra;
          conda deactivate
      # Test Eager
      - name: test eager local
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_eager_local test_eager_sra;
          conda deactivate
      # Test Eager
      - name: test eager sra
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_eager_sra;
          conda deactivate
      # Test snippy pairwise
      - name: test snippy pairwise assembly
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_snippy_pairwise_assembly;
          conda deactivate
      - name: test snippy pairwise sra
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_snippy_pairwise_bam_sra;
          conda deactivate
      # Test snippy pairwise
      - name: test snippy pairwise local
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_snippy_pairwise_bam_local;
          conda deactivate
      # Test snippy multi
      - name: test snippy multi
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_snippy_multi test_snippy_multi_filter;
          conda deactivate
      # Test IQTREE
      - name: test iqtree
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_iqtree;
          conda deactivate
      # Test IQTREE
      - name: test multiqc
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --profile profiles/gh-actions --use-conda --conda-frontend mamba test_multiqc;
          conda deactivate
      # Test Report Generation
      - name: test report
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake --report workflow/report/report.html all;
          conda deactivate
      #------------------------------------------------------------------------#
      #  Artifact Upload
      - name: artifact report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: workflow/report/report.html
