#------------------------------------------------------------------------------#
name: Pipeline
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    CONDA_PREFIX: "/home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/conda"
    SINGULARITY_PREFIX: "/home/runner/work/plague-phylogeography/plague-phylogeography/.snakemake/singularity/"
    TEST_DOWNLOAD: "test_download_reference test_download_assembly test_download_sra test_download_gff test_download_gbff"
    TEST_EAGER: "test_eager_local test_eager_sra"
    TEST_SNIPPY: "test_snippy_pairwise_assembly test_snippy_pairwise_sra test_snippy_pairwise_local"
    TEST_SNIPPY_MULTI: "test_snippy_multi test_snippy_multi_filter"
    TEST_PHYLOGENY: "test_iqtree"
    TEST_QC: "test_multiqc"

#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*/*.yaml'
      - 'workflow/envs/*/Dockerfile'
      - 'workflow/scripts/*'
      - 'results/sqlite_db/*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  pipeline :
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["conda", "singularity"]
      fail-fast: false
    timeout-minutes: 120
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Setup python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # Setup snakemake
      - name: setup snakemake
        run: pip install snakemake==5.26.0 ftputil==4.0.0
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      #------------------------------------------------------------------------#
      # Install conda environment
      - name: create conda env
        run: mamba env create -f workflow/envs/main/main.yaml
      #------------------------------------------------------------------------#
