#------------------------------------------------------------------------------#
name: Pipeline Database
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
    EAGER_NF_REV:    "7b51863957"
    PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
    GH_RESOURCES:    "--max_memory 6.GB --max_cpus 2"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline_db.yaml'
      - 'config/ncbimeta.yaml'
      - 'main.nf'
      - 'nextflow.config'
      - 'environment.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  database:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      # Install nextflow
      - name: install nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #------------------------------------------------------------------------#
      # Setup conda
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache eager env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
          key: eager-env-${{ runner.os }}-7b51863957

      - name: cache plague-phylogeography env
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
          key: plague-phylogeography-env-${{ runner.os }}-${{ hashFiles('environment.yaml') }}
      #------------------------------------------------------------------------#
      # Check conda environments
      - name: check cache
        run: conda info --envs
      #------------------------------------------------------------------------#
      # Download pipelines and install
      - name: install
        shell: bash -l {0}
        run: scripts/install.sh ${{github.repository}} ${{ github.sha }}
      #------------------------------------------------------------------------#
      #  Create the example database
      - name: pipeline db create
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run -r ${{ github.sha }} ${{github.repository}} \
            --ncbimeta_create example/ncbimeta_test.yaml \
            --ncbimeta_api_param "--force-pause-seconds 0 --email ${{secrets.EMAIL}} --api ${{secrets.NCBI_API}}" \
            --ncbimeta_output_dir test \
            --ncbimeta_sqlite_db test.sqlite \
            --skip_sqlite_import \
            --skip_reference_download \
            --skip_outgroup_download \
            --outdir test \
            ${GH_RESOURCES}
          conda deactivate
      #------------------------------------------------------------------------#
      #  Update the database
      - name: pipeline db update
        shell: bash -l {0}
        run: |
          conda activate ${PHYLO_CONDA_ENV}
          nextflow run -r ${{ github.sha }} ${{github.repository}} \
            --ncbimeta_update example/ncbimeta_test.yaml \
            --ncbimeta_sqlite_db test.sqlite \
            --ncbimeta_output_dir test \
            --ncbimeta_annot example/ncbimeta_test_annot.txt \
            --ncbimeta_annot_table BioSample \
            --sqlite test.sqlite \
            --skip_sqlite_import \
            --skip_reference_download \
            --skip_outgroup_download \
            --outdir test \
            -resume \
            ${GH_RESOURCES}
          conda deactivate
