#------------------------------------------------------------------------------#
name: Pipeline
#------------------------------------------------------------------------------#
# Global workflow environment variables
env:
    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/pipeline.yaml'
      - 'workflow/Snakefile'
      - 'workflow/rules/*.smk'
      - 'workflow/envs/*.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Install dependencies
  install :
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repository
      - name: checkout repo
        uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
      #------------------------------------------------------------------------#
      #  Restore (cache) conda environments
      - name: cache default env
        id: cache-default
        uses: actions/cache@v2
        with:
          path: /home/runner/miniconda/envs/default
          key: snakemake-default-${{ runner.os }}-${{ hashFiles('workflow/envs/default.yaml') }}
      # Check conda environments
      - name: check cache
        run: |
          conda info --envs
      # Create environment (if not cached)
      - name: create default environment
        if: steps.cache-default.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run:
          mamba env create -f workflow/envs/default.yaml
      #------------------------------------------------------------------------#
      #  Test pipeline
      - name: test pipeline
        shell: bash -l {0}
        run:
          conda activate default;
          snakemake all --use-conda --profile profiles/gh-actions;
          snakemake --report report.html;
          conda deactivate;
      #------------------------------------------------------------------------#
      #  Artifact Upload
      - name: artifact report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: workflow/report/report.html
